name: gravitational-imaging
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - lenstronomy
  - jupyter
  - pip
  - pip:
    - pyhalo
    # - git+https://github.com/AstroMusers/mejiro.git