site_name: WashU Gravitational Imaging
theme:
  name: mkdocs
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.betterem


# extra_javascript:
#   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6